codeRIT/hackathon-manager

- README.md
With reference to BrickHack's wiki for detailed configuration notes
> Add deployment notes to readme

- config/initializers/hackathon.rb
- lib/hackathon_manager.rb
- lib/hackathon_manager/engine.rb
From:
* http://rmosolgo.github.io/blog/2017/04/12/watching-files-during-rails-development/
* https://github.com/reactjs/react-rails/blob/0ef92cc50d91501778b3403ffbf7b20e8d485b24/lib/react/rails/railtie.rb#L26
* http://api.rubyonrails.org/classes/ActiveSupport/FileUpdateChecker.html
> Reload config upon hackathon.yml changes

- app/controllers/manage/questionnaires_controller.rb
- app/controllers/questionnaires_controller.rb
- app/models/questionnaire.rb
- app/views/application/_questionnaire_summary.html.haml
- app/views/manage/questionnaires/_form.html.haml
- app/views/questionnaires/_form.html.haml
- db/migrate/20171220042158_add_why_attend_to_questionnaires.rb
- lib/hackathon_manager.rb
- test/controllers/manage/questionnaires_controller_test.rb
- test/controllers/questionnaires_controller_test.rb
- test/dummy/config/hackathon.yml
- test/dummy/db/schema.rb
- test/factories/questionnaire.rb
- test/models/questionnaire_test.rb
Be sure to run rails railties:install:migrations and rails db:migrate after upgrading.
> Add "Why attend" to questionnaire

- app/assets/stylesheets/hackathon_manager/mailer.sass
Misc improvements to make email look much better on mobile, while still looking good on desktop
Reviewed changes using Rails' mail preview & [PutsMail](https://putsmail.com/tests/success)
> Improve email layout with respect to mobile clients

- app/controllers/manage/configs_controller.rb
- app/views/layouts/manage/application.html.haml
- app/views/manage/configs/show.html.haml
- config/routes.rb
- test/controllers/manage/configs_controller_test.rb
> Add configuration overview to manage backend

- app/assets/javascripts/hackathon_manager/manage/lib/setupDataTables.js
- app/assets/stylesheets/hackathon_manager/general/_main.sass
- app/controllers/manage/messages_controller.rb
- app/datatables/message_datatable.rb
- app/models/message.rb
- app/models/questionnaire.rb
- app/views/application/_triggered_email_summary.html.haml
- app/views/manage/bus_lists/_form.html.haml
- app/views/manage/messages/_form.html.haml
- app/views/manage/messages/edit.html.haml
- app/views/manage/messages/index.html.haml
- app/views/manage/messages/show.html.haml
- app/views/manage/questionnaires/index.html.haml
- app/views/manage/questionnaires/show.html.haml
- db/migrate/20180108231420_add_trigger_to_message.rb
- test/controllers/manage/messages_controller_test.rb
- test/dummy/db/schema.rb
- test/models/message_test.rb
- test/models/questionnaire_test.rb
> Automatically send emails upon triggered events

- Gemfile.lock
- app/models/user.rb
- app/views/layouts/manage/application.html.haml
- config/initializers/devise.rb
- config/initializers/doorkeeper.rb
- config/locales/doorkeeper.en.yml
- config/routes.rb
- db/migrate/20181221194407_create_doorkeeper_tables.rb
- db/migrate/20181221195241_enable_pkce.rb
- hackathon_manager.gemspec
- lib/hackathon_manager/engine.rb
- test/dummy/db/schema.rb
- test/factories/temp_doorkeeper.rb
- test/integration/oauth_test.rb
* Adds OAuth2 support, managed by [doorkeeper](https://github.com/doorkeeper-gem/doorkeeper)
* Enables access to hackathon_manager routes when authenticating via OAauth2 tokens
> Enable OAuth2 integrations via Doorkeeper

- app/views/rsvps/show.html.haml
Would you be interested in being a bus captain?
No, thank you.
(There should be a comma)
> Grammar Fix

- app/controllers/manage/trackable_tags_controller.rb
- app/models/trackable_event.rb
- app/views/manage/trackable_tags/_form.html.haml
- app/views/manage/trackable_tags/index.html.haml
- app/views/manage/trackable_tags/show.html.haml
- db/migrate/20190213233902_add_prevent_duplicate_band_events_to_trackable_tags.rb
- test/dummy/db/schema.rb
- test/factories/trackable_tag.rb
- test/models/trackable_event_test.rb
Fixes #100
cc @chrisbaudouinjr
> Add option to block duplicate band IDs per trackable tag

- app/views/mailer/bus_captain_confirmation_email.html.erb
- app/views/mailer/bus_list_update_email.html.erb
> remove fixed code url

- app/views/manage/configs/_config_row.html.haml
- app/views/manage/configs/index.html.haml
> [improvement] Better listing display of environment var config

- app/views/layouts/_header.html.haml
- config/app.yml
> Homepage url

- README.md
- app.json
- app/mailers/user_mailer.rb
- app/views/manage/configs/index.html.haml
- app/views/manage/questionnaires/_history.html.haml
- config/environments/production.rb
- docs/deployment-environment-variables.md
> feat: Support SMTP as an alternative email provider to Sparkpost

- app/assets/javascripts/manage/lib/setupDataTables.js
- app/datatables/admin_datatable.rb
- app/helpers/hackathon_manager_helper.rb
- app/views/manage/admins/index.html.haml
- app/views/manage/admins/show.html.haml
> feat: Display sign-in info on the admin detail & admin table list

- app/assets/stylesheets/manage.sass
- app/datatables/checkin_datatable.rb
- app/datatables/questionnaire_datatable.rb
Add center class to be accessible for the datatables and remove the icon-space-r to properly center the text and favicon
> fix: fix position of favicon to be centered for better UX in datatables

- app/controllers/manage/application_controller.rb
- app/controllers/manage/data_exports_controller.rb
- app/jobs/generate_data_export_job.rb
- app/models/data_export.rb
- app/views/layouts/manage/application.html.haml
- app/views/manage/data_exports/_form.html.haml
- app/views/manage/data_exports/index.html.haml
- app/views/manage/data_exports/new.html.haml
- config/routes.rb
- db/migrate/20200205160318_create_data_exports.rb
- db/schema.rb
- test/factories/data_export.rb
- test/jobs/generate_data_export_job_test.rb
- test/models/data_export_test.rb
> feat(exports): Add ability to generate data exports for sponsors

- app/views/manage/questionnaires/_form.html.haml
- config/locales/en.yml
> fix: Fixes label mismatch with dietary restrictions

- app/views/manage/checkins/index.html.haml
Changes "In?" to be "Checked in?"
> style(check-in): Changes table header to be more descriptive

- Gemfile.lock
> fix(deps): Updates the locked Ruby version

- app/controllers/users_controller.rb
- app/models/user.rb
New JSON that adds "questionnaire_id":
```
{
"id": 1,
"created_at": "2020-10-16T20:29:44.000-07:00",
"updated_at": "2020-11-01T18:30:52.000-08:00",
"email": "chrisb@coderit.org",
"provider": null,
"uid": null,
"reminder_sent_at": "2020-10-16T20:29:45.000-07:00",
"role": "director",
"is_active": true,
"receive_weekly_report": false,
"first_name": "Chris",
"last_name": "Baudouin",
"questionnaire_id": null
}
```
closes #393
> feat: Adds "questionnaire_id" to User.as_json

- app/controllers/users_controller.rb
- app/models/message.rb
- app/models/questionnaire.rb
- app/models/user.rb
- app/views/layouts/manage/application.html.haml
- test/models/questionnaire_test.rb
Seeing if the manage folders are the only place to rebrand or if it should be other places as well.
> Refactored "Applications" to "Questionnaires" (#326)

- app/assets/stylesheets/manage.sass
- app/assets/stylesheets/manage/dashboard.css
- app/views/layouts/manage/application.html.haml
Fixes #380 
Fixes scrolling on sidebar mobile view under manage
> bug: Fixes scrolling on sidebar mobile view under manage

- .github/workflows/release.yml
> feat: Adds GitHub Action for releases

- app/models/agreement.rb
Fixes #450 
See issue for before
> Fix agreement label break line bug on mobile

- app/assets/javascripts/validate.js
- app/controllers/manage/agreements_controller.rb
- app/models/agreement.rb
- app/views/manage/agreements/_form.html.haml
- app/views/manage/agreements/index.html.haml
- config/locales/en.yml
- db/migrate/20201130220942_create_agreements.rb
- db/migrate/20201218010133_convert_agreements_to_text.rb
- db/schema.rb
- test/controllers/manage/agreements_controller_test.rb
- test/factories/agreement.rb
- test/models/agreement_test.rb
> feat: Allows agreements to be fully customizable

- app/assets/javascripts/validate.js
- app/controllers/manage/agreements_controller.rb
- app/models/agreement.rb
- app/models/questionnaire.rb
- app/views/devise/registrations/new.html.haml
- app/views/doorkeeper/authorizations/error.html.haml
- app/views/manage/agreements/_form.html.haml
- app/views/manage/agreements/index.html.haml
- config/locales/en.yml
- db/migrate/20201218010133_convert_agreements_to_text.rb
- db/schema.rb
- test/controllers/manage/agreements_controller_test.rb
- test/factories/agreement.rb
- test/models/agreement_test.rb
* fix(questionnaire): missing information now in correct place (#443)
* fix(questionnair): missing information now in correct place
it now displays the correct message "Please read & accept" instead of
missing information and the notification is now in the correct place
* Update app/assets/javascripts/validate.js
* Revert "Update app/assets/javascripts/validate.js"
This reverts commit bc54783f94d7a249ae878ad4ead6a9fb2173fee7.
Signed-off-by: Peter Kos <pkos91@icloud.com>
Co-authored-by: Peter Kos <pkos91@icloud.com>
* fix: Fixes mobile agreements layout bug
Signed-off-by: Peter Kos <pkos91@icloud.com>
* feat: Removes semantic-release (#446)
* refactor: Moves CI to develop branch (#449)
Co-authored-by: Peter Kos <pkos91@icloud.com>
* build: Merges 2.1.2 into develop
* fix(hakiri): corrected …
> master <- develop (2.1.2) (#472)

- CHECKS
> build: Reduces CHECKS attempts from 300 to 100

- .github/workflows/build.yml
> build: Updates GitHub Actions to work on all version branches

- app/mailers/user_mailer.rb
Fixes the issue where RSVP Reminder emails were being sent to already RSVP attendees. 
fixes #555
> fix: Fixes RSVP Reminder email being sent to RSVP attendees

- config/locales/en.yml
old:
Any special needs or requests
new:
> refactor(questionnaire): changed special needs placeholder
