codeRIT/hackathon-manager

- .rubocop-shared.yml
- app/views/layouts/hackathon_manager.html.haml
- lib/hackathon_manager/engine.rb
Turns out we were serving a ton of extra CSS & JS on pages where it wasn't necessary
Side note: we should standardize our naming convention for what's considered public-facing/base/"core" assets vs. management-only assets
> Remove management assets from public-facing pages

- app/views/bus_lists/show.html.haml
- app/views/mailer/_questions.html.erb
- app/views/mailer/bus_captain_confirmation_email.html.erb
- app/views/mailer/rsvp_confirmation_email.html.erb
- test/dummy/config/hackathon.yml
In the future this should be a UI-configurable section. (#14)
Also remove BrickHack-specific notes from default email templates, which included the travel email address. This completely removes the need to specify a travel email address in the gem's configuration; the only places it would appear are in these now-configurable notes, or the already-customizable email templates.
>  Add config for bus captain notes

- app/assets/stylesheets/hackathon_manager/core.sass
- app/assets/stylesheets/hackathon_manager/general/_flashes.sass
- app/assets/stylesheets/hackathon_manager/manage.sass
- app/assets/stylesheets/variables.sass
- app/views/layouts/hackathon_manager/_flashes.html.haml
- app/views/layouts/hackathon_manager/application.html.haml
- app/views/layouts/manage/application.html.haml
- app/views/manage/dashboard/index.html.haml
- app/views/manage/questionnaires/_form.html.haml
- app/views/manage/questionnaires/index.html.haml
- app/views/manage/schools/merge.html.haml
- app/views/manage/stats/index.html.haml
- app/views/questionnaires/_form.html.haml
- app/views/questionnaires/show.html.haml
- app/views/rsvps/show.html.haml
Fixes #50 
Results in something like this:
> Use consistent flash support on all pages

- app/models/message.rb
- app/models/message_recipient_query.rb
- app/views/manage/messages/_form.html.haml
- app/workers/bulk_message_worker.rb
- db/migrate/20180118035548_convert_message_recipients_to_recipient_queries.rb
- test/models/message_test.rb
- test/workers/bulk_message_worker_test.rb
No longer restricted to hard-coded schools and bus list IDs
Also finally added tests for what is probably one of the most important background jobs: actually processing who to send mass email to.
Ultimately for monitoring & bug recovery, there should be a full log of every email that goes out (and who receives it). But tests are a good start.
> Flexible recipient options for all schools & bus lists

- app/assets/stylesheets/general/_flashes.sass
- app/assets/stylesheets/general/_variables.sass
- app/controllers/manage/messages_controller.rb
- app/controllers/manage/questionnaires_controller.rb
- app/controllers/manage/schools_controller.rb
- app/controllers/rsvps_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/views/layouts/_flashes.html.haml
- app/views/layouts/manage/_flashes.html.haml
- test/controllers/manage/messages_controller_test.rb
- test/controllers/manage/questionnaires_controller_test.rb
- test/controllers/rsvps_controller_test.rb
> [improvement] Separate info from error flash notices

- app/views/devise/registrations/_form.html.haml
- app/views/devise/sessions/_form.html.haml
> feat: Hide MyMLH button if MLH_KEY env var is not set

- config/locales/en.yml
Found a tiny typo when using the app, figured I'd fix it. I also ran the rest of the locale text through a spell-checker and didn't come up with anything else.
> fix: Typo in the Bus Captain Notes config description

- .travis.yml
Travis CI doesn't auto-start databases anymore; we have to explicitly specify MySQL as a dependent service
https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
> ci: Fix MySQL support for Travis CI builds

- app/controllers/rsvps_controller.rb
A very simple alert is set before the user is redirect to new questionnaire page if they have not been accepted.
Fixes #32
> feat: Inform user if redirected when trying to RSVP

- app/controllers/manage/configs_controller.rb
- test/controllers/manage/configs_controller_test.rb
> fix: Validate asset config values are URLs

- app/assets/stylesheets/forms/_forms.sass
> fix(questionnaire): School autocomplete matches form field width

- app/views/manage/dashboard/map_data.tsv.erb
Simple swap of latitude and longitude. Must've made an error when we switched Geocoding APIs.
fixes #323
> fix(Dashboard): Fixes missing location data in map

- app/assets/javascripts/manage/map.js
When hovering over a country in the Dashboard Map it'll now display "Questionnaires: x" rather than "Applications: x".
closes #325
> refactor: Changes "Applications" to "Questionnaires" in map

- Gemfile
- Gemfile.lock
- app/controllers/questionnaires_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/models/user.rb
- app/views/application/_questionnaire_summary.html.haml
- app/views/manage/questionnaires/_overview.html.haml
- app/views/questionnaires/_form.html.haml
- Updates MyMLH to V3
- Moves `shirt_size`, `dietary_restrictions` and `special_needs` to event-specific questions
- Updates `manage/questionnaire/#/show` to display `Shirt size` under Special notices rather than Personal information
- Updates omniauth-mlh to 0.4.1
- Fixes issue where provider data wasn't being recorded
- Fixes MyMLH branding. Was: "My MLH" Now: "MyMLH"
| Before | After |
| --- | --- |
| <img width="696" alt="image" src="https://user-images.githubusercontent.com/22222538/90305182-b401e700-de8d-11ea-9649-da8ed908d5e9.png"> | <img width="683" alt="image" src="https://user-images.githubusercontent.com/22222538/90305216-2c68a800-de8e-11ea-9541-b63b7ce9d849.png"> |
| <img width="680" alt="image" src="https://user-images.githubusercontent.com/22222538/90305168-93399180-de8d-11ea …
> feat: Updates MyMLH to V3

- docs/docs-overview.md
- website/pages/en/index.js
- website/sidebars.json
- website/siteConfig.js
> refactor: Renames "Guides" to "Docs"

- docs/deployment-dokku.md
- Adds information about the GitHub Student Developer Pack cloud options to Dokku Deployment
- Cleans the Dokku Deployment docs
closes #343
> refactor: Adds GSDP info, cleans Dokku docs

- app/assets/stylesheets/forms/_forms.sass
- app/views/devise/passwords/edit.html.haml
- app/views/devise/passwords/new.html.haml
- app/views/devise/registrations/new.html.haml
- app/views/devise/sessions/new.html.haml
- app/views/questionnaires/new.html.haml
Fixes #223 
Short hackathon names are on newline:
Long hackathon names wrap in a centered way while maintaining existing container width:
Similar pages match this newline style even if they do not use hackathon name (only password reset and devise edit form)
> fix: Hackathon names now consistently on newline, wrapping is centered

- app/views/questionnaires/new.html.haml
Long container forms have left aligned text while previous PR #358 maintains that small forms have linebreak
> fix: Text centering on application page 

- app/controllers/users_controller.rb
- config/routes.rb
- test/controllers/users_controller_test.rb
Fixes #222  
New route `/user.json` that, when a user is signed in, returns user data:
```json
{
"id": 4582,
"created_at": "2019-12-05T21:26:22.000Z",
"updated_at": "2020-09-20T07:55:36.000Z",
"email": "pkos99@gmail.com",
"provider": null,
"uid": null,
"reminder_sent_at": "2019-12-05T21:26:22.000Z",
"role": "admin_limited_access",
"is_active": true,
"receive_weekly_report": false,
"first_name": "Peter",
"last_name": "Kos"
}
```
Notes:
- Restricted to **json format only** as no frontend exists for this feature
- I had to bypass devise's registration controller because it wouldn't allow me to create a `show` method in there, nor would the devise route handle an incoming `GET`
> Create /user.json get route + test

- app/views/layouts/manage/application.html.haml
Fixes #362 
Added an `Account` button that redirects an organizer back to their account page.
Also flipped the order of "sign out" and the hamburger menu on mobile (before was hamburger, then sign out):
Another bug I just found: while this _works_ on mobile, the sidebar itself is utterly broken! It can't scroll. Also, having a destructive action (sign out) next to the action item (menu button) is... strange. Both of these are addressed in #380
> Link back to user account page from manage added

- app/models/message.rb
- app/models/questionnaire.rb
- test/models/questionnaire_test.rb
Adds the ability for messages to be sent once an attendee(questionnaire) is marked as checked-in.
> feat(Messages): Adds checked in message trigger

- app/controllers/manage/configs_controller.rb
- test/controllers/manage/configs_controller_test.rb
Only enforces the agreement asset to be set. All other assets in config are allowed to be optional.
fixes #405
> fix: Allows optional assets to be unset

- app/views/manage/configs/index.html.haml
Removes an extra space in the MyMLH environment variables.
fixes #411
> fix: Fixes MyMLH branding in config

- app/controllers/manage/configs_controller.rb
- app/views/manage/configs/index.html.haml
Adds section titles and subtitles for the settings page. Better organizes configs and removes excess information.
**Before**
**After**
closes #239
> feat(settings): Simplifies Config

- app/views/application/_questionnaire_summary.html.haml
- app/views/layouts/manage/application.html.haml
- app/views/manage/dashboard/index.html.haml
- app/views/manage/questionnaires/_form.html.haml
- app/views/manage/questionnaires/_overview.html.haml
- app/views/manage/stats/index.html.haml
- app/views/questionnaires/_form.html.haml
- app/views/rsvps/show.html.haml
- config/app.yml
- config/locales/en.yml
Removes sections and verbiage relating to travel. Only affects the view layer.
closes #378
> feat: Adds support for digital-only hackathons

- app/controllers/manage/configs_controller.rb
- app/views/manage/configs/index.html.haml
- config/app.yml
- config/locales/en.yml
> refactor: Removes legal section from config

- app/assets/stylesheets/manage.sass
Overflow auto removed the unnecessary scroll bars around the map when on desktop but keeps them on mobile when they are needed 
before:
after:
> fix(map): changed map overflow from scroll to auto

- app/assets/javascripts/validate.js
- app/views/questionnaires/_form.html.haml
it now displays the correct message "Please read & accept" instead of
missing information and the notification is now in the correct place
> fix(questionnaire): missing information now in correct place

- app/views/doorkeeper/authorizations/error.html.haml
fixed the cross-site scripting warning by removing the raw component since un-escaped string are not a requirement for door keeper error message to work
> fix(hakiri): corrected unescaped model attribute

- app/views/devise/registrations/new.html.haml
> fix: Shows questionnaires_closed_message on registration

- app/views/doorkeeper/authorizations/error.html.haml
removed the html_safe. this no longer makes the hackathon name bold but removes the security error
Before
After
> fix(hakiri): fix hakiri error with user input in html_safe

- docs/docs-overview.md
- docs/users-and-staff.md
- website/sidebars.json
Adds docs for the Users & Staff page. Contains description of the page along with a detailed table on each role and their permissions.
Preview:
[Users & Staff · HackathonManager.pdf](https://github.com/codeRIT/hackathon-manager/files/5742672/Users.Staff.HackathonManager.pdf)
closes #357
> feature: Adds Users & Staff docs

- app/controllers/questionnaires_controller.rb
- config/locales/en.yml
Checks to see if any of the required MyMLH data is null. If true, we display an error that instructs the user to continue manually. 
fixes #515 
Edit flow: 
After you auth via MyMLH, it will attempt to skip the first page, whether the info exists or not, triggering the frontend validation.
If no info is missing, it will skip to page 2 of the questionnaire form.
If info is missing, due to the triggered validation, it will **attempt to pull as many fields as possible**, and highlight the missing field(s):
> fix: Resolves issue preventing new MyMLH users from creating questionnaires

- app/controllers/questionnaires_controller.rb
Fixes #492 
changed from redirect_to to render "edit" on error. redirect_to makes a fresh request which causes the error information to be lost well render keeps the information
> fix: vcs url error not displaying in edit application page

- app/controllers/questionnaires_controller.rb
- config/locales/en.yml
- Fix MyMLH not providing all info crash
- Properly show error on user edit page when VCS URL is incorrect
> 2.1.4 <- develop

- app/mailers/user_mailer.rb
Simple blank? check to make sure the questionnaire isn't nil before we execute the RSVP reminder email job. This is currently causing failing jobs in Sidekiq. 
fixes #528
> fix: Resolves job execution failure on nil questionnaires

- app/assets/stylesheets/manage.sass
- app/views/manage/agreements/index.html.haml
since the table is set to have equal spacing between elements and there are so view elements, width had to be manually set for the first element to make it look normal
before:
after:
fixes #438
> fix(agreements): decreased distance between icons

- app/controllers/events_controller.rb
- app/models/event.rb
- config/routes.rb
- test/controllers/events_controller_test.rb
api now returns null instead of empty string for optional fields and added a public facing api
> fix(events): fixed api to be public and have blank strings be null

- app/models/questionnaire.rb
- app/views/rsvps/show.html.haml
the error is now in a box like that of agreements and not the custom error message from the model. also disabled rsvp and bus update button if the user questionnaire is invalid.
> refactor(questionnaire): changed questionnaire missing info error

- .github/workflows/build.yml
Caches the Ruby gems to prevent installs for each run.
> build(deps): Updates GitHub Actions to cache gems

- app/controllers/manage/questionnaires_controller.rb
- test/controllers/manage/questionnaires_controller_test.rb
Adds proper API support for the check_in route, accessing the route through the API format will no longer respond with a redirect and will respond with a 204 upon success.  
closes #615
> feat: Adds API support for checking attendees in

- app/controllers/manage/events_controller.rb
- test/controllers/manage/events_controller_test.rb
known issue: organizers clicking on a event item brings them to the dashboard as they don't have edit permissions
> fix(schedule): orginizers now have read only access

- app/views/manage/questionnaires/_form.html.haml
fixed the whitespace which was caused by label being a empty string instead of false so the label space was still there. The agreements were also re added although disabled for a director to change.
new:
previous:
possible alternative:
> fix(questionnaire): fixed whitespace and readded agreements to edit page

- app/views/manage/questionnaires/edit.html.haml
Replaced delete button styling from btn-secondary-outline to btn-danger-outline.
If there are more necessary changes to the coloring or styling of this button, let me know.
> design(Questionnaire): Changed class of delete questionnaire button to btn-outline-danger

- app/jobs/generate_data_export_job.rb
- app/models/data_export.rb
Fixes missing user's name migration from #222, fixes race condition where the controller wasn't updating the queued_at timestamp before the job started. This caused the job to think it was a duplicate export.
fixes #534
> fix: Fixes missing name error and race condition in data exports

- app/controllers/manage/questionnaires_controller.rb
- config/locales/en.yml
- test/controllers/manage/questionnaires_controller_test.rb
Current:
"Checked in Chris Baudouin"
"Chris Baudouin no longer checked in" <- sounds like the user here is an object.
New:
"Chris Baudouin has been checked in"
"Chris Baudouin is no longer checked in"
closes #621
> refactor: Updates check-in/out flash verbiage
